version: '3'

services:
  rails:
    ports:
      - "8000:3000"  # Изменен внешний порт на 8000
    environment:
      - FRONTEND_URL=http://0.0.0.0:8000
      
  # Mailhog уже определен в основном docker-compose.yaml файле,
  # поэтому мы можем просто переопределить порты если нужно
  mailhog:
    ports:
      - "8025:8025"  # Веб-интерфейс для просмотра писем
      - "1025:1025"  # SMTP порт
